### ISSUE TITLE
Error while validating Config: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Malte-Sc** [vmware-labs/hci-benchmark-appliance#1]
### Describe the bug

I have configured the HCI Benchmark appliance and clicked on verify. While checking I get an Error: 
===================================================================================

2023-10-30 12:05:41 +0000: Validating Fio binary and the workload profiles...
2023-10-30 12:05:41 +0000: Validating VC IP and Credential...
2023-10-30 12:05:45 +0000: VC IP and Credential Validated
2023-10-30 12:05:45 +0000: Validating Datacenter Site01...
2023-10-30 12:05:45 +0000: Datacenter Site01 Validated
2023-10-30 12:05:45 +0000: Validating Cluster Cluster01...
2023-10-30 12:05:45 +0000: Cluster Cluster01 Validated
2023-10-30 12:05:45 +0000: Cluster Cluster01 has DRS mode: fullyAutomated
2023-10-30 12:05:45 +0000: Validating If Any Hosts in Cluster Cluster01 for deployment is in Maintainance Mode...
2023-10-30 12:05:48 +0000: Validating VM Folder HCIBENCH...
2023-10-30 12:05:48 +0000: VM Folder HCIBENCH validated
2023-10-30 12:05:48 +0000: Validating Network dpg_test...
2023-10-30 12:05:48 +0000: Network dpg_test Validated, type is DistributedVirtualPortgroup
2023-10-30 12:05:48 +0000: Checking If Network dpg_test is accessible from all the hosts for deployment...
2023-10-30 12:05:49 +0000: Network dpg_test is accessible from all the hosts for deployment
2023-10-30 12:05:49 +0000: Datastore Cluster01-vSANDatastore Validated
2023-10-30 12:05:49 +0000: Checking Datastore Cluster01-vSANDatastore type...
2023-10-30 12:05:49 +0000: Datastore Cluster01-vSANDatastore type is vsan
2023-10-30 12:05:49 +0000: Getting Datastore Cluster01-vSANDatastore id...
2023-10-30 12:05:49 +0000: Checking If Datastore Cluster01-vSANDatastore is accessible from any of the hosts of Cluster01...
2023-10-30 12:05:50 +0000: Datastore Cluster01-vSANDatastore is accessible from hosts esx24.company.local, esx17.company.local, esx25.company.local, esx27.company.local, esx16.company.local, esx15.company.local, esx26.company.local, esx14.company.local
2023-10-30 12:05:51 +0000: vSAN is Enabled in Cluster Cluster01, the vSAN Datastore for test is Cluster01-vSANDatastore
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbcae4b]

goroutine 1 [running]:
github.com/vmware/govmomi/govc/datastore/vsan.(*info).Run(0xc00000e640, 0x14feb40, 0xc000038050, 0xc00008a7e0, 0x0, 0x0)
/opt/go/src/github.com/vmware/govmomi/govc/datastore/vsan/info.go:207 +0xf5b
github.com/vmware/govmomi/govc/cli.Run(0xc000032080, 0x6, 0x6, 0xc0000a2058)
/opt/go/src/github.com/vmware/govmomi/govc/cli/command.go:165 +0x5de
main.main()
/opt/go/src/github.com/vmware/govmomi/govc/main.go:104 +0x64
/usr/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)
from /usr/lib/ruby/2.5.0/json/common.rb:156:in `parse'
from /opt/automation/lib/rvc-util.rb:703:in `_get_vsan_stats'
from /opt/automation/lib/rvc-util.rb:716:in `_get_vsan_default_policy'
from /opt/automation/lib/pre-validation.rb:241:in `block in validate_vsan_info'
from /opt/automation/lib/pre-validation.rb:240:in `each'
from /opt/automation/lib/pre-validation.rb:240:in `validate_vsan_info'
from /opt/automation/lib/pre-validation.rb:634:in `

===================================================================================

Here is the Config I used:
![image](https://github.com/vmware-labs/hci-benchmark-appliance/assets/31400720/5268a673-ba4d-4fa0-8e9f-738b1ef919a0)

### Reproduction steps

1. Configure HCI Benchmark
2. Click on Save Config
3. Click on Validate Config, a Popup will show with the error above
...

### Expected behavior

Verify should be fine

**Comment by Malte-Sc** [comment]
nvm, seesm to be an permissions issue
